name: sunwhirlv1
description: "A Flutter application to visualize sun and shadows on a map."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  mapbox_maps_flutter: ^2.7.0
  provider: ^6.1.2
  http: ^1.2.1
  intl: ^0.19.0
  url_launcher: ^6.3.0
  image: ^4.1.7

  geolocator: ^12.0.0
  permission_handler: ^11.3.1

  # UI helpers
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
